### ISSUE TITLE
[Phonon] Traceback on _inicializar_sistema_de_audio

### ISSUE THREAD

**Issue by juancarlospaco** [hugoruscitti/pilas#249]
```python
Error: 
Traceback (most recent call last):
  File "/usr/local/bin/pilas", line 7, in <module>
    pilas.utils.iniciar_asistente_desde_argumentos()
  File "/usr/local/lib/python2.7/dist-packages/pilas/utils.py", line 504, in iniciar_asistente_desde_argumentos
    app = pilas.abrir_interprete(do_raise=True, con_aplicacion=True)
  File "/usr/local/lib/python2.7/dist-packages/pilas/__init__.py", line 239, in abrir_interprete
    interprete.main(parent, do_raise)
  File "/usr/local/lib/python2.7/dist-packages/pilas/interprete.py", line 232, in main
    ui.setupUi(main, ejecutar_codigo_inicial=True)
  File "/usr/local/lib/python2.7/dist-packages/pilas/interprete.py", line 37, in setupUi
    scope = self._insertar_ventana_principal_de_pilas(ejecutar_codigo_inicial)
  File "/usr/local/lib/python2.7/dist-packages/pilas/interprete.py", line 162, in _insertar_ventana_principal_de_pilas
    pilas.iniciar(usar_motor='qtsugargl', ancho=640, alto=400)
  File "/usr/local/lib/python2.7/dist-packages/pilas/__init__.py", line 89, in iniciar
    motor = _crear_motor(usar_motor, permitir_depuracion, audio)
  File "/usr/local/lib/python2.7/dist-packages/pilas/__init__.py", line 172, in _crear_motor
    motor = motor_qt.Motor(usar_motor, permitir_depuracion, audio)
  File "/usr/local/lib/python2.7/dist-packages/pilas/motores/motor_qt.py", line 1037, in __init__
    self._inicializar_sistema_de_audio(audio)
  File "/usr/local/lib/python2.7/dist-packages/pilas/motores/motor_qt.py", line 1080, in _inicializar_sistema_de_audio
    raise Exception("Error, el sistema de audio pygame no esta disponible")
Exception: Error, el sistema de audio pygame no esta disponible
```

```python
juan@x:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4 import phonon
>>> phonon
<module 'PyQt4.phonon' from '/usr/lib/python2.7/dist-packages/PyQt4/phonon.so'>
>>>
```

This if-else on _inicializar_sistema_de_audio() is failing to use Phonon for audio:
- https://github.com/hugoruscitti/pilas/blob/master/pilas/motores/motor_qt.py#L1069

![temp](https://cloud.githubusercontent.com/assets/1189414/3398298/b48810fc-fd2d-11e3-90cd-99c1776ff70d.jpg)

- The .DEB packages depend on Phonon, so it should be first intead of PyGames ?

:octocat:

**Comment by hugoruscitti** [comment]
Ya no usamos mas phonon, cierro el bug.
