### ISSUE TITLE
pilas does not running because that a resource is not found.

### ISSUE THREAD

**Issue by echevemaster** [hugoruscitti/pilas#257]
this is the traceback, this issue is at 0.90.26 version

```bash
libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
loaded the Generic plugin 
Traceback (most recent call last):
  File "/usr/bin/pilasengine", line 8, in <module>
    pilasengine.utils.iniciar_desde_terminal()
  File "/usr/lib/python2.7/site-packages/pilasengine/utils/__init__.py", line 277, in iniciar_desde_terminal
    _ = pilasengine.abrir_asistente()
  File "/usr/lib/python2.7/site-packages/pilasengine/__init__.py", line 555, in abrir_asistente
    return asistente.abrir()
  File "/usr/lib/python2.7/site-packages/pilasengine/asistente/__init__.py", line 224, in abrir
    ui.setupUi(MainWindow)
  File "/usr/lib/python2.7/site-packages/pilasengine/asistente/__init__.py", line 108, in setupUi
    self._cargar_pagina_principal()
  File "/usr/lib/python2.7/site-packages/pilasengine/asistente/__init__.py", line 176, in _cargar_pagina_principal
    file_path = pilasengine.utils.obtener_ruta_al_recurso('asistente/index.html')
  File "/usr/lib/python2.7/site-packages/pilasengine/utils/__init__.py", line 142, in obtener_ruta_al_recurso
    raise IOError("El archivo '%s' no existe." % (ruta))
IOError: El archivo 'asistente/index.html' no existe.
```

**Comment by arkhan** [comment]
I have the same problem in archlinux with the version 1.0.0
I download the file: https://github.com/hugoruscitti/pilas/archive/1.0.0.zip and execute the comands

python2 setup.py install --prefix=/usr

**Comment by hugoruscitti** [comment]
related #276
