### ISSUE TITLE
Error al agregar fondo

### ISSUE THREAD

**Issue by aarondiazr** [hugoruscitti/pilas#264]
Hola, tengo el siguiente problema...
Cuando quiero agregar un fondo ya sea un jpg o png, siempre me marca el siguiente error:

QPainter::end: Painter ended with 3 saved states
ERROR integer division or modulo by zero
-310
Traceback (most recent call last):
  File "./pilasengine/__init__.py", line 402, in realizar_dibujado
    self.escenas.realizar_dibujado(painter)
  File "./pilasengine/escenas/__init__.py", line 85, in realizar_dibujado
    escena.dibujar_actores(painter)
  File "./pilasengine/escenas/escena.py", line 110, in dibujar_actores
    x.dibujar(painter)
  File "./pilasengine/fondos/desplazamiento_horizontal.py", line 56, in dibujar
    capa.dibujar_tiled_horizontal(painter, ancho, alto)
  File "./pilasengine/fondos/desplazamiento_horizontal.py", line 81, in dibujar_tiled_horizontal
    dx = self.x % self.imagen.ancho()
ZeroDivisionError: integer division or modulo by zero

**Comment by hugoruscitti** [comment]
Hola, ¿nos enviarías el código con el que construyes el fondo?

**Comment by aarondiazr** [comment]
solo escribi esto (basandome en los ejemplos)

```python
import pilasengine

pilas = pilasengine.iniciar()

fondo = pilas.fondos.DesplazamientoHorizontal()

fondo.agregar('9135_funny_minimal.jpg', velocidad=0)

pilas.ejecutar()
```

**Comment by hugoruscitti** [comment]
Era un problema con la velocidad en 0, sorry, recién está solucionado.
