### ISSUE TITLE
Error inicializando box2d -- 1.3.2 (rpm, fedora) y 1.4.3 (git)

### ISSUE THREAD

**Issue by martin-langhoff** [hugoruscitti/pilas#286]
Sobre Fedora 23 he instalado pilas 1.3.2 via rpm y via git (con las instrucciones de virtualenv). En ambos casos pilasengine arranca al menu de inicio, pero llamando al editor o los ejemplos falla en un loop; el error, repetido al infinito, es el de abajo:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 117, in timerEvent
    self.procesar_error(e)
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 101, in procesar_error
    escena = self.pilas.escenas.Error(titulo, descripcion)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 118, in metodo_crear_escena
    raise TypeError(str(error) + mensaje_extendido)
TypeError: __init__() takes exactly 4 arguments (3 given)
	(en la clase Error solo se deberia esperar el argumento pilas
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 114, in metodo_crear_escena
    nueva_escena = clase_de_la_escena(self.pilas)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/escena.py", line 55, in __init__
    self.fisica = Fisica(self, pilas)
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 42, in __init__
    self.mundo = box2d.b2World(gravedad, True)
TypeError: __init__() takes exactly 4 arguments (3 given)

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 117, in timerEvent
    self.procesar_error(e)
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 101, in procesar_error
    escena = self.pilas.escenas.Error(titulo, descripcion)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 118, in metodo_crear_escena
    raise TypeError(str(error) + mensaje_extendido)
TypeError: __init__() takes exactly 4 arguments (3 given)
	(en la clase Error solo se deberia esperar el argumento pilas
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 114, in metodo_crear_escena
    nueva_escena = clase_de_la_escena(self.pilas)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/escena.py", line 55, in __init__
    self.fisica = Fisica(self, pilas)
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 42, in __init__
    self.mundo = box2d.b2World(gravedad, True)
TypeError: __init__() takes exactly 4 arguments (3 given)

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 117, in timerEvent
    self.procesar_error(e)
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 101, in procesar_error
    escena = self.pilas.escenas.Error(titulo, descripcion)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 118, in metodo_crear_escena
    raise TypeError(str(error) + mensaje_extendido)
TypeError: __init__() takes exactly 4 arguments (3 given)
	(en la clase Error solo se deberia esperar el argumento pilas

```

En mi lectura inicial hay 2 problemas:

 * Algo en la inicializacion de box2d tiene el nro de parametros incorrecto, el paquete pybox2d en F23 es `2.0.2b2`. Que version necesita?
* El manejo del error es... malo :-)

**Comment by hugoruscitti** [comment]
Hola @martin-langhoff, efectivamente pilas no detecta correctamente la versión de box2d y falla a causa de eso. Pilas necesita usar versiones posteriores a la 2.1 de box2d (ya que cambió la api interna de box2d a partir de esa versión).

Usando el comando "pilas -t" debería detectar eso, y dar un mensaje de error claro. Pero si, es cierto que debería detectarlo el propio poner al inicializar la ventana o antes. Me lo agendo para implementar :) 

No se muy bien cómo se podría hacer para instalar una versión nueva de box2d en Fedora, pero supongo que en el peor de los casos se debería hacer una compilación manual, aquí hay algunos ejemplos de cómo hacerlo:

https://github.com/hugoruscitti/pilas/wiki/instalacion

**Comment by martin-langhoff** [comment]
Gracias @hugoruscitti ! Buen dato. Yo tengo buen toolchain de fedora asi que voy a ver de actualizar pybox2d generando un rpm para actualizar dentro de Fedora.

Ahi vi 2.3.1 de pybox2d asi que en marcha...

**Comment by martin-langhoff** [comment]
Con 2.3.1 compilado e instalado...

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 117, in timerEvent
    self.procesar_error(e)
  File "/usr/lib/python2.7/site-packages/pilasengine/widget.py", line 101, in procesar_error
    escena = self.pilas.escenas.Error(titulo, descripcion)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/__init__.py", line 114, in metodo_crear_escena
    nueva_escena = clase_de_la_escena(self.pilas)
  File "/usr/lib/python2.7/site-packages/pilasengine/escenas/escena.py", line 56, in __init__
    self.fisica.iniciar()
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 59, in iniciar
    self.crear_bordes_del_escenario()
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 63, in crear_bordes_del_escenario
    self.crear_techo(self.area)
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 158, in crear_techo
    self.techo = self.Rectangulo(0, alto/2, ancho, 2, dinamica=False, plataforma=True, restitucion=restitucion)
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/__init__.py", line 317, in Rectangulo
    plataforma=plataforma)
  File "/usr/lib/python2.7/site-packages/pilasengine/fisica/rectangulo.py", line 53, in __init__
    restitution=restitucion)
  File "/usr/lib64/python2.7/site-packages/Box2D/Box2D.py", line 4851, in __init__
    _init_kwargs(self, **kwargs)
  File "/usr/lib64/python2.7/site-packages/Box2D/Box2D.py", line 152, in _init_kwargs
    raise AttributeError('Invalid keyword argument "%s" for %s' % (key, cls))
AttributeError: Invalid keyword argument "linearDamping" for <class 'Box2D.Box2D.b2FixtureDef'>


```

**Comment by hugoruscitti** [comment]
Uh, que raro @martin-langhoff ... ¿que te imprime el comando pilas -t desde bash?.

En mi caso aparece:

```
➤ python bin/pilasengine -t
Realizando pruebas de dependencias:

Box 2D: OK, versión 2.3b0
pyqt: OK, versión 4.11.4
pyqt con aceleracion: OK
pygame: OK
```

¿y corriendo los tests?:

```
➤ make utest
```

**Comment by martin-langhoff** [comment]
`make utest` da el mismo error con `linearDamping`. La única diferencia es que tengo Box 2D version 2.3.1. Tal vez cambió la API?

**Comment by hugoruscitti** [comment]
Hola @martin-langhoff , ahí pude instalar pybox2d 2.3.1 y efectivamente cambió la api, ahora pude reproducir el problema...

Voy a ver si puedo hacerlo compatible con las dos apis, te escribo ante cualquier novedad.

**Comment by martin-langhoff** [comment]
Ok. En cuanto lo tengas resuelto avisame que lo pongo todo actualizado en Fedora. Y se lo instalo a mi sobrino que tiene 12 a~nos y esta metiendose en Python :-)

**Comment by hugoruscitti** [comment]
Listo @martin-langhoff, ahí pude resolverlo. Probá hacer pull de pilas y te va a funcionar bien :)

**Comment by hugoruscitti** [comment]
https://github.com/hugoruscitti/pilas/commit/507b85d8cf03ddf30584b5c6198f65001a3b506f

**Comment by martin-langhoff** [comment]
Funciona! Perfecto, gracias. Tenes planeado un tag&release, pensando en Fedora?

**Comment by hugoruscitti** [comment]
Oh, buenisimo !!!

si, ahora que me confirmaste armé el tag 1.4.4:

https://github.com/hugoruscitti/pilas/tree/1.4.4

Gracias!!

**Comment by martin-langhoff** [comment]
Perfecto! en un rato aterriza en F24 (todavia en beta).

**Comment by hugoruscitti** [comment]
Genial !!!! avisame cualquier cosa que necesites, por acá estoy :)

**Comment by martin-langhoff** [comment]
Update para pybox2d en Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1321662

**Comment by martin-langhoff** [comment]
Dejo nota aca que en base a discussoin en el parche 507b85d estoy esperando un peque~no cambio y tal vez un 1.4.5, con la intencion de ponerlo en Fedora.

**Comment by martin-langhoff** [comment]
@echevemaster - https://bugzilla.redhat.com/show_bug.cgi?id=1321665
